### ISSUE TITLE
How to get in touch regarding a security concern?

### ISSUE THREAD

**Issue by cokeBeer** [dablelv/go-huge-util#5]
Hello 👋

I found a potential security issue in go-huge-util, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**Comment by dablelv** [comment]
Thank u for your issue and advice very much. If you are using wechat, you can add my wechat 18819064334. Besides, you can also contact with me through my email 1589276509@qq.com.

Keep in touch, thx.

**Comment by cokeBeer** [comment]
@dablelv  Hi, emailed you

**Comment by dablelv** [comment]
> @dablelv Hi, emailed you

Thank you for your reminder and the path traversal vulnearbility has been fixed. If you make a PR we will be appreciated more. Thx again.

**Comment by cokeBeer** [comment]
@dablelv Hi, I think it has been fixed. What about publishing a [github security advisory](https://github.com/dablelv/go-huge-util/security/advisories) for this vulnerability ? If you feel confused about some blanks, you can add me as a collaborator.

**Comment by dablelv** [comment]
> 

Great idea! I has invited you as a collaborator on the repository, awaiting for your response.

**Comment by dablelv** [comment]
@cokeBeer Great idea! I has invited you as a collaborator on the repository, awaiting for your response.

**Comment by cokeBeer** [comment]
@dablelv Hi, thanks for your offering. However, there is a misunderstanding that actually I may need a security collaborator on a security advisory for the vulnerability to help edit it.  You can click `draft new security advisory` on this page (https://github.com/dablelv/go-huge-util/security/advisories) to open one and add me a security collaborator on that page. Sorry for my misleading.

**Comment by dablelv** [comment]
I got it. I have created a security advisories and invited you as a&nbsp;collaborator.
&nbsp;


吕吕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dablelv/go-huge-util] How to get in touch regarding a security concern? (Issue #5)





 
@dablelv Hi, thanks for your offering. However, there is a misunderstanding that actually I may need a security collaborator on a security advisory for the vulnerability to help edit it.  You can click draft new security advisory on this page (https://github.com/dablelv/go-huge-util/security/advisories) to open one and add me a security collaborator on that page. Sorry for my misleading.

**Comment by cokeBeer** [comment]
@dablelv 没问题. 用英文在issue区讨论可以让更多人了解内容
